name: Flutter Android/iOS CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false  # Skip submodules if they're problematic
      
      - name: Clean up submodule issues (if any)
        run: |
          # Remove any broken submodule references
          git submodule deinit --all --force || true
          git clean -fd || true
      - name: Install Flutter (Latest Stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          # No version specified = latest stable
      - name: Confirm Flutter & Dart version
        run: |
          flutter --version
          dart --version
          # Verify Dart SDK version is compatible
          dart --version | grep -E "Dart SDK version: [3-9]\.[8-9]|[4-9]\." || (echo "Error: Dart SDK 3.8.1+ required" && exit 1)
      - name: Install dependencies
        run: |
          cd fixbuddy
          flutter pub get
      - name: Run Analyzer
        run: |
          cd fixbuddy
          flutter analyze
      - name: Run Tests
        run: |
          cd fixbuddy
          flutter test
      - name: Build APK
        run: |
          cd fixbuddy
          flutter build apk --release
      - name: Build AppBundle (AAB)
        run: |
          cd fixbuddy
          flutter build appbundle --release